feat(hw): Add mnemos shield
tosc-rs/mnemos pull request #163
Opened 2023-07-16 22:37 UTC by jamesmunns

2023-07-16 23:07 UTC, hawkw requested changes
overall this is great! however, i do wonder if we ought to include a note about the need to physically isolate the 5v rails from the MQ Pro/Beepy?

2023-07-16 23:07 UTC, hawkw commented on hardware/mnemos-shield/README.md
should we maybe include some kind of note about how the 5v rails need to be removed/disabled due to current software limitations? i don't want people frying their SOCs...

2023-07-16 23:15 UTC, jamesmunns commented on hardware/mnemos-shield/README.md
Sure, how far would you like me to go in documenting this?

The connection of the 5v rail is DESIRED when you are not powering the board through the top and bottom of the device at the same time.

We are in the awkward between time where we must have the device tethered to the primary USB cable for programming, and have no persistence.

I could describe all of these options, or I could just go redesign the board to make this a breakable connection, either using a DPDT switch or solder bridge.

In particular, we don't perform WORSE or differently from the existing beepy (you're not supposed to plug into the pi usb ports at all), we are just weird because we HAVE to for ephemeral programming.

2023-07-25 23:35 UTC, hawkw approved these changes
fine to merge this whenever you like btw :)

2023-07-31 18:22 UTC, merged